variables:
  MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"

.test: &test
  stage: test
  script:
    - 'mvn verify site site:stage'
  except:
    - gh-pages
  
before_script:
  - uname -a

test:jdk8:3.5:
  <<: *test
  image: maven:3.5-jdk-8
  artifacts:
    paths:
      - target/staging

test:jdk8:3.3.9:
  <<: *test
  image: maven:3.3.9-jdk-8

pages:
  image: alpine
  stage: deploy
  script:
    - mv target/staging public
  dependencies:
    - test:jdk8:3.5
  artifacts:
    paths:
    - public
  only:
    - master

